services:
  - type: web
    name: gemini-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    workingDir: backend
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false   # Set this securely in Render dashboard

  - type: web
    name: gemini-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    workingDir: frontend
